name: xpsitest
channels:
        - defaults
        - conda-forge
dependencies:
        - numpy
        - cython
        - matplotlib
        - scipy
        - wrapt
        - pymultinest  # nested sampling
        - mpi4py  # nested sampling
        - pytest  # running functionality self-tests
        - getdist  # posterior KDE corner plotting
        - h5py  # storage of X-ray signals computed from posterior samples
        - nestcheck  # posterior error analysis, plotting, run combination, etc.
        - fgivenx  # conditional posterior plotting; also required by nestcheck
