name: Build docs

on:
  push:
    branches:
      - main
  release:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        cache-env: true
        cache-env-key: env-envkey-${{ github.sha }}-${{ github.run_attempt }}
        environment-file: basic_environment.yml
        environment-name: xpsipy3
        extra-specs: |
          python=3.10
    - name : install docs dependencies
      run: |
        micromamba install sphinx decorator h5py
        micromamba install -c conda-forge nbsphinx nbconvert
        pip install sphinxcontrib-websupport sphinx_rtd_theme sphinx-multiversion
#    - uses: conda-incubator/setup-miniconda@v2
#      with:
#         activate-environment: xpsipy3
#         environment-file: basic_environment.yml
#         python-version: 3.9
#         auto-activate-base: false
#    - name : install docs dependencies
#      run: |
#        conda install sphinx
#        conda install -c conda-forge nbsphinx
#        conda install -c conda-forge nbconvert
#        conda install decorator
#        conda install h5py
#        pip install sphinxcontrib-websupport
#        pip install sphinx-multiversion
#        pip install sphinx_rtd_theme
    - name: Set up GCC
      run: |
         sudo apt-get install -y gcc
      shell: bash -l {0}
    - name: install gsl
      run: |
        sudo apt-get install -y libgsl-dev
    - name: install X-PSI package
      run: |
        python setup.py install
      shell: bash -l {0}
      env:
        CC:   gcc-10
    - name : build docs
      shell: bash -l {0}
      run: |
        make versions
        #touch build/html/.nojekyll
        cp source/index-redirect.html build/html/index.html
        ln -srf build/html/$(git tag -l --sort=creatordate |tail -1) build/html/latest  # auto-link the latest tag

      working-directory: docs/
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: docs/build/
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
