name: changelog

on:
  pull_request:
    types: [labeled, closed]
jobs:
  check-changelog-entry:
    if: github.event.action == 'labeled' && github.event.label.name == 'ready-for-changelog'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
      - name: Check for changelog fragments
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          if compgen -G "changelog.d/$PR_NUMBER.*.rst"; then
            echo "Changelog exists :)"
          else
            echo "Changelog entry not found! :("
            exit 1
          fi

  generate-changelog:
    runs-on: ubuntu-latest
    needs: check-changelog-entry
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Install changelog dependencies
        run: |
          pip install towncrier

      - name: Build changelog with Towncrier
        run: |
          VERSION=$(grep -oP "^__version__\s*=\s*['\"]\K[^'\"]+" xpsi/__init__.py | cut -d. -f1,2)
          towncrier build --version $VERSION

      - name: Sync with latest PR branch before updating changelog
        run: |
          git fetch origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          git pull origin ${{ github.head_ref }}

      - name: Run Towncrier to generate changelog
        run: |
          towncrier build --yes

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changelog update
        run: |
          git add CHANGELOG.rst
          git commit -m "Changelog updated"
          git push origin HEAD:${{ github.head_ref }}
